logging:
  level:
    root: debug

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: 3runner-auth
  jwt:
    secret: aaaasqwlkljlfasdfqwerafcxvzpojijoijopjewndllllllsserrrrrrwqexc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: dlawjddn

  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 15
      password: "*N2vya7H@muDTwdNMR!"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoint:
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true


server:
  shutdown: graceful
  port: 8090
  netty:
    connection-timeout: 30s
