logging:
  level:
    root: debug

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: 3runner-auth
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@127.0.0.1:8761/eureka
#  instance:
#    prefer-ip-address: true

management:
  endpoint:
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true


server:
  shutdown: graceful
  port: 8090